---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alerts.nais.io
spec:
  group: nais.io
  scope: Namespaced
  names:
    plural: alerts
    singular: alert
    kind: Alert
    shortNames:
      - al
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Team
      type: string
      JSONPath: .metadata.labels.team
  versions:
    - name: "v1alpha1"
      served: false
      storage: false
    - name: "v1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            metadata:
              required:
                - labels
              properties:
                labels:
                  required:
                    - team
                  properties:
                    team:
                      type: string
            spec:
              required:
                - receivers
                - alerts
              properties:
                route:
                  type: object
                  properties:
                    group_wait:
                      type: string
                        pattern: '[0-9]+(ms|[smhdwy])'
                    group_interval:
                      type: string
                      pattern: '[0-9]+(ms|[smhdwy])'
                    repeat_interval:
                      type: string
                      pattern: '[0-9]+(ms|[smhdwy])'
                receivers:
                  type: object
                  properties:
                    slack:
                      type: object
                      properties:
                        channel:
                          type: string
                        prependText:
                          type: string
                    email:
                      type: object
                      properties:
                        to:
                          type: string
                        send_resolve:
                          type: boolean
                    sms:
                      type: object
                      properties:
                        recipients:
                          type: string
                        send_resolve:
                          type: boolean
                    pushover:
                      type: object
                      properties:
                        send_resolve:
                          type: boolean
                        user_key:
                          type: string
                alerts:
                  type: array
                  required:
                    - alert
                    - for
                    - expr
                    - action
                  items:
                    type: object
                    properties:
                      alert:
                        type: string
                      description:
                        type: string
                      expr:
                        type: string
                      for:
                        type: string
                        pattern: '^\d+[smhdwy]$'
                      action:
                        type: string
                      documentation:
                        type: string
                      sla:
                        type: string
                      severity:
                        type: string
                        pattern: '^$|good|warning|danger|#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})'
                inhibitRules:
                  type: array
                  required:
                    - targets
                    - sources
                  items:
                    type: object
                    properties:
                      targets:
                        type: object
                      targetsRegex:
                        type: object
                      sources:
                        type: object
                      sourcesRegex:
                        type: object
                      labels:
                        type: array
                        items:
                          type: string