# permissions for end users to edit alerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alert-editor-role
rules:
- apiGroups:
  - alerterator.nais.io
  resources:
  - alerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alerterator.nais.io
  resources:
  - alerts/status
  verbs:
  - get
