
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alerterator
rules:
- apiGroups:
  - nais.io
  resources:
  - alerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nais.io
  resources:
  - alerts/status
  verbs:
  - get
  - patch
  - update
