name: Build and deploy
on: push

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alerterator
        uses: actions/checkout@v2
      - run: docker build -t docker.pkg.github.com/"$GITHUB_REPOSITORY"/alerterator:$(./version.sh) .
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - run: docker push docker.pkg.github.com/"$GITHUB_REPOSITORY"/alerterator:$(./version.sh)

  nais-yaml:
    name: Release to nais-yaml
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout alerterator
        uses: actions/checkout@v2
        with:
          path: alerterator
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ secrets.NAIS_YAML_TOKEN }}
          path: nais-yaml
      - name: Update nais-yaml
        run: |
          cd alerterator
          version=$(./version.sh)
          
          cat config/deploy/resources.yaml > ../nais-yaml/templates/zz-generated-alerterator.yaml
          cat config/deploy/deployment > ../nais-yaml/templates/alerterator.yaml

          cd ../nais-yaml
          git config user.name alerterator-actions
          git config user.email alerterator-actions@github.com

          sed -E -i "s#image: docker.pkg.github.com/"$GITHUB_REPOSITORY"/alerterator:.+#image: docker.pkg.github.com/"$GITHUB_REPOSITORY"/alerterator:${version}#" vars/alerterator.yaml
          git add .
          git --no-pager diff --cached
          git commit -a -m "Bump Alerterator to version ${version}"
          git push
